export { default as Home } from './Home'
export { default as About } from './About'
export { default as Time } from './Time'
export { default as Courses } from './Courses'
export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Classes } from './Classes'
export { default as Subject } from './Subject'